import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import { formatBRL, formatDateBR, wrapText } from './voucher'

// ============================================================
// Recibo PDF — on-demand proof of payment (Fase 6.2, market-gap plan:
// docs/redesign-2026-plan.md). Unlike the voucher (auto-generated by
// the booking flow and sent over WhatsApp), a recibo is generated on
// request, from a reserva that has actually been paid — never for an
// unpaid one, since a receipt implies money already changed hands
// (PRODUCT.md's "real data or nothing").
// ============================================================

export interface ReciboData {
  agenciaNome: string
  agenciaCnpj: string | null
  agenciaTelefone: string | null
  agenciaEndereco: string | null
  pacoteNome: string
  data: string // YYYY-MM-DD — the service date (passeio), not the payment date
  quantidadePessoas: number
  valor: number
  clienteNome: string | null
  reservaId: string
  paidAt: string | null // ISO timestamp the payment actually confirmed
  logoBytes: Uint8Array | null
}

export function reciboNumero(reservaId: string): string {
  return reservaId.slice(0, 8).toUpperCase()
}

export function reciboFilename(reservaId: string): string {
  return `recibo-${reciboNumero(reservaId)}.pdf`
}

const PAGE_WIDTH = 595.28 // A4 at 72dpi
const PAGE_HEIGHT = 841.89
const MARGIN = 56
const LOGO_MAX = 48

/** Renders the recibo as a one-page A4 PDF — same visual language as the voucher. */
export async function renderReciboPdf(data: ReciboData): Promise<Uint8Array> {
  const doc = await PDFDocument.create()
  const page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)

  let y = 780
  const ink = rgb(0.1, 0.1, 0.12)
  const muted = rgb(0.45, 0.45, 0.48)
  const accent = rgb(0.42, 0.24, 0.9)

  const line = (
    text: string,
    opts: { size?: number; f?: typeof font; color?: ReturnType<typeof rgb>; gap?: number } = {},
  ) => {
    const { size = 11, f = font, color = ink, gap = 18 } = opts
    page.drawText(text, { x: MARGIN, y, size, font: f, color })
    y -= gap
  }

  if (data.logoBytes) {
    try {
      const isPng = data.logoBytes[0] === 0x89
      const image = isPng ? await doc.embedPng(data.logoBytes) : await doc.embedJpg(data.logoBytes)
      const scale = Math.min(LOGO_MAX / image.width, LOGO_MAX / image.height, 1)
      const w = image.width * scale
      const h = image.height * scale
      page.drawImage(image, { x: PAGE_WIDTH - MARGIN - w, y: PAGE_HEIGHT - 40 - h, width: w, height: h })
    } catch {
      // Best-effort, same as the voucher — a bad logo never blocks the document.
    }
  }

  line(data.agenciaNome, { size: 13, f: bold, color: accent, gap: 16 })
  const agencyContactBits = [data.agenciaCnpj && `CNPJ ${data.agenciaCnpj}`, data.agenciaTelefone, data.agenciaEndereco]
    .filter(Boolean)
    .join(' · ')
  if (agencyContactBits) line(agencyContactBits, { size: 8.5, color: muted, gap: 20 })
  else y -= 4

  line('RECIBO DE PAGAMENTO', { size: 20, f: bold, gap: 8 })
  line(`Nº ${reciboNumero(data.reservaId)}`, { size: 10, color: muted, gap: 30 })

  page.drawLine({
    start: { x: MARGIN, y },
    end: { x: PAGE_WIDTH - MARGIN, y },
    thickness: 1,
    color: rgb(0.85, 0.85, 0.87),
  })
  y -= 30

  wrapText(
    `Recebemos de ${data.clienteNome ?? 'cliente'} a quantia de ${formatBRL(data.valor)} referente a "${data.pacoteNome}" (${data.quantidadePessoas} pessoa${data.quantidadePessoas === 1 ? '' : 's'}), passeio marcado para ${formatDateBR(data.data)}.`,
    90,
  ).forEach((row) => line(row, { size: 12, gap: 18 }))

  y -= 12
  const field = (label: string, value: string) => {
    page.drawText(label, { x: MARGIN, y, size: 9.5, font, color: muted })
    page.drawText(value, { x: MARGIN + 130, y, size: 11.5, font: bold, color: ink })
    y -= 24
  }
  field('Valor recebido', formatBRL(data.valor))
  field('Data do pagamento', data.paidAt ? formatDateBR(data.paidAt.slice(0, 10)) : '—')
  field('Cliente', data.clienteNome ?? '—')

  y -= 40
  page.drawLine({ start: { x: MARGIN, y }, end: { x: MARGIN + 220, y }, thickness: 1, color: muted })
  y -= 14
  line(data.agenciaNome, { size: 9.5, color: muted, gap: 14 })

  return doc.save()
}
